name: stage distribution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Node Install
        run: |
          npm install --force

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Run Test
        run: npm test

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew assembleStageRelease --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-stage-release.apk
          path: android/app/build/outputs/apk/stage/release/

      - name: Upload artifact to Firebase App Distribution
        id: testing_outputs
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          serviceCredentialsFileContent: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          groups: ${{ secrets.GROUP_NAME }}
          file: android/app/build/outputs/apk/stage/release/app-stage-release.apk
