name: stage distribution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Node Install
        run: |
          npm install

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Run Test
        run: npm test

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew assembleStageRelease --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-stage-release.apk
          path: android/app/build/outputs/apk/stage/release/


      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > firebase-service-account.json
          FIREBASE_TOKEN=$(npx firebase login:ci --json | jq -r .token)
          echo "::set-output name=FIREBASE_CLI_TOKEN::$FIREBASE_TOKEN"
        env:
          FIREBASE_CLI_TOKEN: ${{ steps.authenticate.outputs.FIREBASE_CLI_TOKEN }}

      - name: Deploy to Firebase
        run: |
          npx firebase deploy --only hosting --token $FIREBASE_CLI_TOKEN

      - name: Build and Distribute
        env:
          FIREBASE_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          APP_ID: ${{ secrets.APP_ID }}
          GROUP_NAME: ${{ secrets.GROUP_NAME }}
          notes: ${{ github.event.head_commit.message }}
        # uses: wzieba/Firebase-Distribution-Github-Action@v1
        # with:
        #   appId: ${{ secrets.APP_ID }}
        #   # token: "$(echo $FIREBASE_SA_KEY | base64 --decode)"
        #   groups: ${{ secrets.GROUP_NAME }}
        #   file: android/app/build/outputs/apk/stage/release/app-stage-release.apk

          
        run: |
          if [ "${{ github.event.inputs.environment }}" == "staging" ]; then
            echo "Deploying to staging..."
            firebase appdistribution:distribute \
              android/app/build/outputs/apk/stage/release/app-stage-release.apk \
              --app ${{ secrets.APP_ID }} \
              --groups ${{ secrets.GROUP_NAME }} \
              --token "$(echo $FIREBASE_SA_KEY | base64 --decode)"
          elif [ "${{ github.event.inputs.environment }}" == "production" ]; then
            echo "Deploying to production..."
            firebase appdistribution:distribute \
              android/app/build/outputs/apk/dev/release/app-stage-release.apk \
              --app ${{ secrets.APP_ID }} \
              --groups ${{ secrets.GROUP_NAME }} \
              --token "$(echo $FIREBASE_SA_KEY | base64 --decode)"
          else
            echo "Invalid environment specified."
            exit 1
          fi
